### ISSUE TITLE
Jaxon-Upload Help

### ISSUE THREAD

**Issue by kskelton2021** [jaxon-php/jaxon-core#105]
X

**Comment by kskelton2021** [comment]
Fatal error: Uncaught Error: Call to undefined function Jaxon\jaxon() in C:\local_html\assets\vendors\jaxon\4.1\vendor\jaxon-php\jaxon-upload\src\start.php:86 Stack trace: #0 C:\local_html\assets\vendors\jaxon\4.1\vendor\jaxon-php\jaxon-upload\src\start.php(115): Jaxon\Upload\registerUpload() #1 C:\local_html\assets\vendors\jaxon\4.1\vendor\composer\autoload_real.php(71): require('C:\\local_html\\a...') #2 C:\local_html\assets\vendors\jaxon\4.1\vendor\composer\autoload_real.php(61): composerRequire6f29c6aaaf0c99b4ad9f337b5330997f('6d2ef7af76d0237...', 'C:\\local_html\\a...') #3 C:\local_html\assets\vendors\jaxon\4.1\vendor\autoload.php(7): ComposerAutoloaderInit6f29c6aaaf0c99b4ad9f337b5330997f::getLoader() #4 C:\local_html\configs\jaxon.php(2): require('C:\\local_html\\a...') #5 C:\local_html\includes\autoloader.inc.php(37): require('C:\\local_html\\c...') #6 C:\local_html\index.php(11): include('C:\\local_html\\i...') #7 {main} thrown in C:\local_html\assets\vendors\jaxon\4.1\vendor\jaxon-php\jaxon-upload\src\start.php on line 86
