### ISSUE TITLE
options.filter is not a function when using getFormValues with a multiple-select

### ISSUE THREAD

**Issue by walmartshopper** [jaxon-php/jaxon-core#128]
I am trying to convert a large old codebase from Xajax 0.5 to Jaxon 4.8.0.  When I try to call a jaxon function with getFormValues, and the form contains a multiple-select, I am getting a JS error:

```
Uncaught TypeError: options.filter is not a function
    at _getValue (jaxon.core.js:507:21)
    at jaxon.core.js:559:12
    at NodeList.forEach (<anonymous>)
    at _getValues (jaxon.core.js:554:18)
    at jaxon.core.js:557:17
    at NodeList.forEach (<anonymous>)
    at _getValues (jaxon.core.js:554:18)
    at jaxon.core.js:557:17
    at NodeList.forEach (<anonymous>)
    at _getValues (jaxon.core.js:554:18)
```

Here is a sample PHP file that reproduces the issue:

```
<?php

  require_once("$path/vendor/autoload.php");
  use Jaxon\Jaxon;
  use function Jaxon\jaxon;

  $jaxon = jaxon();
  $jaxon->register(Jaxon::CALLABLE_FUNCTION, 'save');
  if($jaxon->canProcessRequest())
    $jaxon->processRequest();

  function save($form)
  {
    $response = jaxon()->newResponse();
    $response->alert(print_r($form, 1));
    return $response;
  }
?>

<html>
<head>
<?php print $jaxon->getScript(true, true); ?>
</head>
<body>
  <form id='test_form'>
    <select multiple="multiple" name="multiselect">
      <option value="1">Value 1</option>
      <option value="2">Value 2</option>
      <option value="3">Value 3</option>
    </select>
    <button type='button' onclick="jaxon_save(jaxon.getFormValues('test_form'));">Submit</button>
  </form>
</body>
</html>
```

EDIT: I tried version 3.8.2 and no longer get this error.  Downgrading to 3.8.2 also fixed a JS error when I tried to turn on debugging, plus the error below, which I am not sure how to reproduce.

```
Uncaught TypeError: rsp.process is not a function
    at jaxon.core.js:1241:52
```

**Comment by feuzeu** [comment]
Hi,

This issu is fixed in this release: https://github.com/jaxon-php/jaxon-core/releases/tag/v4.8.1.
